# Generated by Django 3.1.3 on 2020-12-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sender_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='to',
            field=models.CharField(default=5, max_length=30),
        ),
    ]
