# Generated by Django 3.1.3 on 2020-12-25 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user1_user2_user3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User1',
        ),
        migrations.DeleteModel(
            name='User2',
        ),
        migrations.DeleteModel(
            name='User3',
        ),
    ]
